[package]
name = "tombolo"
description = "The terminal window."
version.workspace = true
edition.workspace = true

[[bin]]
name = "tombolo"
path = "src/main.rs"

[dependencies]
core-vt = { path = "../core-vt" }
pty = { path = "../pty" }

[target.'cfg(windows)'.dependencies]
windows.workspace = true
windows-core.workspace = true
windows-numerics.workspace = true
